development: &default
  adapter: postgresql
  database: intercity-next_development
  encoding: utf8
  host: <%= ENV["DB_HOST"] || "localhost" %>
  min_messages: warning
  pool: 2
  timeout: 5000
  username: <%= ENV["DB_USER"] || "root" %>

test:
  <<: *default
  database: intercity-next_test

production:
  <<: *default
  database: intercity
  host: <%= ENV["DB_SOCKET"] %>
  pool: 50
