schedule_automated_backups:
  cron: "0 */1 * * *"
  class: "ScheduleAutomatedBackupsJob"
  queue: default
  active_job: true
schedule_health_checks:
  cron: "0,30 * * * *"
  class: "ScheduleHealthChecksJob"
  queue: health_checks
  active_job: true
